// This file is generated by tools/gen_operators.pl. CHANGES WILL BE OVERWRITTEN
/*  Copyright (C) 2013-2014  Povilas Kanapickas <povilas@radix.lt>

    Distributed under the Boost Software License, Version 1.0.
        (See accompanying file LICENSE_1_0.txt or copy at
            http://www.boost.org/LICENSE_1_0.txt)
*/

#ifndef LIBSIMDPP_SIMDPP_CORE_I_SHIFT_R_OPERATOR_H
#define LIBSIMDPP_SIMDPP_CORE_I_SHIFT_R_OPERATOR_H

#ifndef LIBSIMDPP_SIMD_H
    #error "This file must be included through simd.h"
#endif

#include <simdpp/types.h>
#include <simdpp/detail/insn/i_shift_r.h>

namespace simdpp {
namespace SIMDPP_ARCH_NAMESPACE {

} // namespace SIMDPP_ARCH_NAMESPACE
} // namespace simdpp

#endif

