// This file is generated by tools/gen_operators.pl. CHANGES WILL BE OVERWRITTEN
/*  Copyright (C) 2013-2014  Povilas Kanapickas <povilas@radix.lt>

    Distributed under the Boost Software License, Version 1.0.
        (See accompanying file LICENSE_1_0.txt or copy at
            http://www.boost.org/LICENSE_1_0.txt)
*/

#ifndef LIBSIMDPP_SIMDPP_CORE_I_SHIFT_L_OPERATOR_H
#define LIBSIMDPP_SIMDPP_CORE_I_SHIFT_L_OPERATOR_H

#ifndef LIBSIMDPP_SIMD_H
    #error "This file must be included through simd.h"
#endif

#include <simdpp/types.h>
#include <simdpp/detail/insn/i_shift_l.h>

namespace simdpp {
#ifndef SIMDPP_DOXYGEN
namespace SIMDPP_ARCH_NAMESPACE {
#endif

/// @{
/** Shifts 8-bit values left by @a count bits while shifting in zeros.

    @code
    r0 = a0 << count
    ...
    rN = aN << count
    @endcode


    @par 128-bit version:
    @icost{SSE2-AVX, 4-5}
    @icost{NEON, 1-2}
    @icost{ALTIVEC, 1-4}

    @par 256-bit version:
    @icost{SSE2-AVX, 8-9}
    @icost{AVX2, 4-5}
    @icost{NEON, 2-3}
    @icost{ALTIVEC, 2-5}
*/
#if SIMDPP_DOXYGEN
template<unsigned N, class E>
int8<N, _DETAIL_> operator<<(int8<N,E> a, unsigned count);

template<unsigned N, class E>
uint8<N, _DETAIL_> operator<<(uint8<N,E> a, unsigned count);
#else
template<unsigned N, class E> SIMDPP_INL
int8<N, int8<N>> operator<<(int8<N,E> a, unsigned count)
{
    uint8<N> qa = a.eval();
    return detail::insn::i_shift_l(qa, count);
}

template<unsigned N, class E> SIMDPP_INL
uint8<N, uint8<N>> operator<<(uint8<N,E> a, unsigned count)
{
    return detail::insn::i_shift_l(a.eval(), count);
}
#endif
/// @}

/// @{
/** Shifts 16-bit values left by @a count bits while shifting in zeros.

    @code
    r0 = a0 << count
    ...
    rN = aN << count
    @endcode

    @par 128-bit version:
    @icost{NEON, 1-2}
    @icost{ALTIVEC, 1-4}

    @par 256-bit version:
    @icost{SSE2-AVX, 2}
    @icost{NEON, 2-3}
    @icost{ALTIVEC, 2-5}
*/
#if SIMDPP_DOXYGEN
template<unsigned N, class E>
int16<N, _DETAIL_> operator<<(int16<N,E> a, unsigned count);

template<unsigned N, class E>
uint16<N, _DETAIL_> operator<<(uint16<N,E> a, unsigned count);
#else
template<unsigned N, class E> SIMDPP_INL
int16<N, int16<N>> operator<<(int16<N,E> a, unsigned count)
{
    uint16<N> qa = a.eval();
    return detail::insn::i_shift_l(qa, count);
}

template<unsigned N, class E> SIMDPP_INL
uint16<N, uint16<N>> operator<<(uint16<N,E> a, unsigned count)
{
    return detail::insn::i_shift_l(a.eval(), count);
}
#endif
/// @}

/// @{
/** Shifts 32-bit values left by @a count bits while shifting in zeros.

    @code
    r0 = a0 << count
    ...
    rN = aN << count
    @endcode

    @par 128-bit version:
    @icost{NEON, 1-2}
    @icost{ALTIVEC, 1-4}

    @par 256-bit version:
    @icost{SSE2-AVX, 2}
    @icost{NEON, 2-3}
    @icost{ALTIVEC, 2-5}
*/
#if SIMDPP_DOXYGEN
template<unsigned N, class E>
int32<N, _DETAIL_> operator<<(int32<N,E> a, unsigned count);

template<unsigned N, class E>
uint32<N, _DETAIL_> operator<<(uint32<N,E> a, unsigned count);
#else
template<unsigned N, class E> SIMDPP_INL
int32<N, int32<N>> operator<<(int32<N,E> a, unsigned count)
{
    uint32<N> qa = a.eval();
    return detail::insn::i_shift_l(qa, count);
}

template<unsigned N, class E> SIMDPP_INL
uint32<N, uint32<N>> operator<<(uint32<N,E> a, unsigned count)
{
    return detail::insn::i_shift_l(a.eval(), count);
}
#endif
/// @}

/// @{
/** Shifts 64-bit values left by @a count bits while shifting in zeros.

    @code
    r0 = a0 << count
    ...
    rN = aN << count
    @endcode

    @par 128-bit version:
    @icost{NEON, 1-2}
    @unimp{ALTIVEC}

    @par 256-bit version:
    @icost{SSE2-AVX, 2}
    @icost{NEON, 2-3}
    @unimp{ALTIVEC}
*/
#if SIMDPP_DOXYGEN
template<unsigned N, class E>
int64<N, _DETAIL_> operator<<(int64<N,E> a, unsigned count);

template<unsigned N, class E>
uint64<N, _DETAIL_> operator<<(uint64<N,E> a, unsigned count);
#else
template<unsigned N, class E> SIMDPP_INL
int64<N, int64<N>> operator<<(int64<N,E> a, unsigned count)
{
    uint64<N> qa = a.eval();
    return detail::insn::i_shift_l(qa, count);
}

template<unsigned N, class E> SIMDPP_INL
uint64<N, uint64<N>> operator<<(uint64<N,E> a, unsigned count)
{
    return detail::insn::i_shift_l(a.eval(), count);
}
#endif
/// @}

/// @{
/// @}

/// @{
/// @}

/// @{
/// @}

/// @{
/// @}

#ifndef SIMDPP_DOXYGEN
} // namespace SIMDPP_ARCH_NAMESPACE
#endif
} // namespace simdpp

#endif

